tab_spaces = 2
trailing_semicolon = true
use_field_init_shorthand = true

reorder_impl_items = true
reorder_imports = true
reorder_modules = true

wrap_comments = true
comment_width = 100
max_width = 100
format_code_in_doc_comments = true